#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2010-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

if [ $# -ne 2 ]; then
    echo "Create a plot the rate of transactions."
    echo "usage: `basename $0` <mix.log> <output directory>"
    echo
    echo "    <mix.log> - full path to the mix.log file"
    echo "    <output directory> - location to write output files"
    echo
    echo "Will attempt to create <output directory> if it does not exist."
    exit 1
fi

INFILE=$1
OUTDIR=$2

if [ ! -f "${INFILE}" ]; then
    echo "cannot open file: ${INFILE}"
	exit 1
fi

mkdir -p ${OUTDIR}
if [ ! -d "${OUTDIR}" ]; then
	echo "cannot create directory ${OUTDIR}"
fi

R --slave --no-save << __EOF__
# Is there an escape error in pipe()? It shouldn't print the START marker line
# nor the TERMINATED line.
cmd <- "sed -n '/START/,/TERMINATED/{/START|TERMINATED/!p}' ${INFILE}"
df <- read.csv(pipe(cmd), header=F)
df <- df[-1,]
df <- df[-nrow(df),]
total_txn <- nrow(df)

sd <- 0
bv <- 1
cp <- 2
mw <- 3
ts <- 4
tl <- 5
to <- 6
tu <- 7
mf <- 8
tr <- 9
dm <- 10
tc <- 11
transaction_list <- c(sd, bv, cp, mw, ts, tl, to, tu, mf, tr, dm)

txn <- c("sd", "bv", "cp", "mw", "ts", "tl", "to", "tu", "mf", "tr", "dm")
txn_name <- c("Security Detail", "Broker Volume", "Customer Position",
              "Market Watch", "Trade Status", "Trade Lookup", "Trade Order",
              "Trade Update", "Market Feed", "Trade Result", "Data Maintenance")

# Get the ctime after the START marker and the ctime before the first
# TERMINATED marker.
starttime <- df[1,]\$ctime
endtime <- df[total_txn:total_txn,]\$ctime

color <- rainbow(length(txn_name))

colnames(df)[1] <- 'ctime'
colnames(df)[2] <- 'txn'
# This is really the transaction "status" column, but we're going to count the
# number of occurances here.
colnames(df)[3] <- 'count'

starttime = df[1,]\$ctime

# Aggregate counts by into minutes.
df\$ctime <- ceiling((df\$ctime - starttime) / 60)
df <- aggregate(count ~ txn + ctime, df, length)

for (key in 1:length(transaction_list) - 1) {
  bitmap(paste("${OUTDIR}/", txn[key + 1], "-transaction-rate.png", sep = ""),
         type="png16m", units="px", width=1280, height=800, res=150, taa=4,
         gaa=4)
  dfsub <- subset(df, df\$txn == key)
  plot(dfsub\$ctime, dfsub\$count, xlim=c(0, max(dfsub\$ctime)),
       ylim=c(0, max(dfsub\$count)), type="b", col=color[key + 1],
       main=paste(txn_name[key + 1], " Transaction Rate", sep=""),
       xlab="Elapsed Time (minutes)", ylab="Transactions per Minute")
  grid(col="gray")
  invisible(dev.off())
}
__EOF__
